-- Insert SQL Rules Here 
INSERT INTO UnitPromotions (Type, Description, Help, Sound, PortraitIndex, IconAtlas, CannotBeChosen, PediaType, PediaEntry)
VALUES (PROMOTION_HORN_HUNTER, TXT_KEY_PROMOTION_HORN_HUNTER, TXT_KEY_PROMOTION_HORN_HUNTER_HELP, AS2D_IF_LEVELUP, 44, PROMOTION_ATLAS,
true, PEDIA_TERRAIN, TXT_KEY_PROMOTION_HORN_HUNTER_PEDIA_ENTRY).
