
#define WOTMOD 0
#define SIEGEMOD 0
#define CUSTOM_NOTIFICATIONS 0
#define CUSTOM_MISSIONS 0

#ifdef ENABLE_CUSTOM_NOTIFICATIONS
	#define CUSTOM_NOTIFICATIONS 1
#endif // ENABLE_CUSTOM_NOTIFICATIONS

#ifdef ENABLE_CUSTOM_MISSIONS
	#define CUSTOM_MISSIONS 1
#endif // CUSTOM_MISSIONS

#ifdef ENABLE_SIEGEMOD
	#define WOTMOD 0
	#define SIEGEMOD 1
	#define CUSTOM_NOTIFICATIONS 1
	#define CUSTOM_MISSIONS 1
#endif // ENABLE_SIEGEMOD

#ifdef ENABLE_WOTMOD
	#define WOTMOD 1
	#define SIEGEMOD 1
	#define CUSTOM_NOTIFICATIONS 1
	#define CUSTOM_MISSIONS 1
#endif // ENABLE_WOTMOD